AgjensioniUdhetimit_ProjektiTI2/Controllers/BookingController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AgjensioniUdhetimit_ProjektiTI2.Models;
using AgjensioniUdhetimit_ProjektiTI2.Services;

namespace AgjensioniUdhetimit_ProjektiTI2.Controllers
{
    [Authorize]
    public class BookingController : Controller
    {
        BookingService bookingService = new BookingService();

        // GET: Booking
        public ActionResult Index()
        {
            return View(BookingService.GetAllBookings());
        }

        // GET: Booking/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Booking/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Booking/Create
        [HttpPost]
        public ActionResult Create(Booking booking)
        {
            if (ModelState.IsValid)
            {
                  bookingService.Insert(booking);
                  return RedirectToAction("Index");
            }
             return View(booking);
        }

        // GET: Booking/Edit/5
        public ActionResult Edit(int id)
        {
            return View(bookingService.GetBookingById(id));
        }

        // POST: Booking/Edit/5
        [HttpPost]
        public ActionResult Edit(Booking booking)
        {
            try
            {
                bookingService.Update(booking);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Booking/Delete/5
        public ActionResult Delete(int id)
        {
            return View(bookingService.GetBookingById(id));
        }

        // POST: Booking/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                bookingService.Delete(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

    }
}

AgjensioniUdhetimit_ProjektiTI2/Controllers/ClientsController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading;
using System.Web;
using System.Web.Mvc;
using AgjensioniUdhetimit_ProjektiTI2.Models;
using AgjensioniUdhetimit_ProjektiTI2.Services;

namespace AgjensioniUdhetimit_ProjektiTI2.Controllers
{
    [Authorize]
    public class ClientsController : Controller
    {
        ClientService clientService = new ClientService();
        Client client = new Client();
        // GET: Clients
        public ActionResult Index()
        {
            return View(ClientService.GetAllClients());
        }
        

        // GET: Clients/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Clients/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Clients/Create
        [HttpPost]
        public ActionResult Create(Client client)
        {
                if (ModelState.IsValid)
                {
                    clientService.Insert(client);
                    return RedirectToAction("Index");
                }
            
                return View(client);
        }

        public ActionResult Edit(int id)
        {
            return View(clientService.GetClientByID(id));
        }

        //// POST: Clients/Edit/5
        [HttpPost]
        public ActionResult Edit(Client client)
        {
            try
            {
                clientService.Update(client);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //GET
        public ActionResult Delete(int id)
        {
            return View(clientService.GetClientByID(id));
        }

        // POST: Clients/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection formCollection)
        {
            try
            {
                clientService.Delete(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

       

    }
}

AgjensioniUdhetimit_ProjektiTI2/Controllers/StaffController.cs
using AgjensioniUdhetimit_ProjektiTI2.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AgjensioniUdhetimit_ProjektiTI2.Models;

namespace AgjensioniUdhetimit_ProjektiTI2.Controllers
{
    [Authorize]
    public class StaffController : Controller
    {
        StaffService staffService = new StaffService();
        //RoleService roleService = new RoleService();
        // GET: Staff
        public ActionResult Index()
        {
            return View(staffService.GetAllStaff());
        }

        // GET: Staff/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Staff/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Staff/Create
        [HttpPost]
        public ActionResult Create(Staff staff)
        {
            if (ModelState.IsValid)
            {
                staffService.Insert(staff);
                return RedirectToAction("Index");
            }
            return View(staff);
        }

        // GET: Staff/Edit/5
        public ActionResult Edit(int id)
        {
            return View(staffService.GetStaffById(id));
        }

        // POST: Staff/Edit/5
        [HttpPost]
        public ActionResult Edit(Staff staff)
        {
            try
            {
                staffService.EditStaff(staff);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Staff/Delete/5
        public ActionResult Delete(int id)
        {
            return View(staffService.GetStaffById(id));
        }

        // POST: Staff/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                staffService.Delete(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

       

        public ActionResult GetAllStaff()
        {
            List<Staff> staff = staffService.GetAllStaff();
            return Json(new { data = staff }, JsonRequestBehavior.AllowGet);
        }

    }
}

AgjensioniUdhetimit_ProjektiTI2/Controllers/TicketController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AgjensioniUdhetimit_ProjektiTI2.Models;
using AgjensioniUdhetimit_ProjektiTI2.Services;

namespace AgjensioniUdhetimit_ProjektiTI2.Controllers
{
    [Authorize]
    public class TicketController : Controller
    {
        TicketService ticketService = new TicketService();
        // GET: Ticket
        public ActionResult Index()
        {
            return View(ticketService.GetAllTickets());
        }

        // GET: Ticket/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Ticket/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Ticket/Create
        [HttpPost]
        public ActionResult Create(Ticket ticket)
        {
            if (ModelState.IsValid)
            {
                ticketService.InsertTicket(ticket);
                return RedirectToAction("Index");
            }
            return View(ticket);
        }

        // GET: Ticket/Edit/5
        public ActionResult Edit(int id)
        {
            return View(ticketService.GetTicketByID(id));
        }

        // POST: Ticket/Edit/5
        [HttpPost]
        public ActionResult Edit(Ticket ticket)
        {
            try
            {
                ticketService.Update(ticket);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Ticket/Delete/5
        public ActionResult Delete(int id)
        {
            return View(ticketService.GetTicketByID(id));
        }

        // POST: Ticket/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                ticketService.Delete(id);
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        public ActionResult GetAllTickets()
        {
            List<Ticket> ticket = ticketService.GetAllTickets();
            return Json(new { data = ticket }, JsonRequestBehavior.AllowGet);
        }
    }
}

AgjensioniUdhetimit_ProjektiTI2/Views/Shared/_Layout.cshtml
 <!DOCTYPE html>
 <html lang="en">
 <head>
     <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <title>@ViewBag.Title - Travel Agency</title>
 </head>
 <body>
     @if (User.Identity.IsAuthenticated)
     {
         <header>
             <nav class="navbar navbar-expand-lg navbar-light bg-light">
                 <a href="#" style="margin-left:5%">
                     @Html.ActionLink(AgjensioniUdhetimit_ProjektiTI2.Resources.Content.Travel_Agency, "Index", "Home", new { area = "" }, new { @class = "navbar-brand text-secondary" })
                 </a>
                 <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                         aria-controls="#navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                     <span class="navbar-toggler-icon"></span>
                 </button>
                 <div class="collpase navbar-collapse">
                     <ul class="navbar-nav mr-auto">
                         <li class="nav-item">@Html.ActionLink(AgjensioniUdhetimit_ProjektiTI2.Resources.Content.Clients, "Index", "Clients", null, new { @class = "nav-link" })</li>
                         <li class="nav-item">@Html.ActionLink(AgjensioniUdhetimit_ProjektiTI2.Resources.Content.Staff, "Index", "Staff", null, new { @class = "nav-link" })</li>
                         <li class="nav-item">@Html.ActionLink(AgjensioniUdhetimit_ProjektiTI2.Resources.Content.Booking, "Index", "Booking", null, new { @class = "nav-link" })</li>
                         <li class="nav-item">@Html.ActionLink(AgjensioniUdhetimit_ProjektiTI2.Resources.Content.Ticket, "Index", "Ticket", null, new { @class = "nav-link" })</li>
                     </ul>
                     <ul class="nav navbar-nav navbar-right">
                         <li>@Html.ActionLink(AgjensioniUdhetimit_ProjektiTI2.Resources.Content.EN, "ChangeLanguage", "Language", null ,new { language = "en-US" ,@class = "nav-link"})</li>
                         <li>@Html.ActionLink(AgjensioniUdhetimit_ProjektiTI2.Resources.Content.AL, "ChangeLanguage", "Language", null ,new { language = "sq-AL", @class = "nav-link" })</li>
                     </ul>
                     @Html.Partial("_LoginPartial") 
                 </div>
             </nav>
         </header>
     }
     <div class="container body-content">
         @RenderBody()
         @if (User.Identity.IsAuthenticated)
         {
             <footer class="page-footer mt-5" id="footer">
                 <div class="container">
                     <div class="row justify-content-center mb-5">
                         <div class="col-lg-3 py-3">
                             <h3>Travel Agency</h3>
                             <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit.</p>
                             <p><a href="mailto:travelagency@gmail.com">travelagency@gmail.com</a></p>
                             <p><a href="#">+00 1122 3344 5566</a></p>
                         </div>
                         <div class="col-lg-3 py-3">
                             <h5>Quick Links</h5>
                             <ul class="footer-menu">
                                 <li><a href="#">How it works</a></li>
                                 <li><a href="#">Security</a></li>
                                 <li><a href="#">Pricing</a></li>
                                 <li><a href="#">Resources</a></li>
                                 <li><a href="#">Report a Bug</a></li>
                             </ul>
                         </div>
                         <div class="col-lg-3 py-3">
                             <h5>About Us</h5>
                             <ul class="footer-menu">
                                 <li><a href="#">About Us</a></li>
                                 <li><a href="#">Jobs</a></li>
                                 <li><a href="#">Our Teams</a></li>
                                 <li><a href="#">Testimonials</a></li>
                                 <li><a href="#">News & Press</a></li>
                             </ul>
                         </div>
                         <div class="col-lg-3 py-3">
                             <h5>Subscribe</h5>
                             <form action="#">
                                 <input type="text" class="form-control" placeholder="Enter your mail..">
                             </form>
                             <div class="sosmed-button mt-4">
                                 <a href="#"><span class="mai-logo-facebook-f"></span></a>
                                 <a href="#"><span class="mai-logo-twitter"></span></a>
                                 <a href="#"><span class="mai-logo-google"></span></a>
                                 <a href="#"><span class="mai-logo-linkedin"></span></a>
                             </div>
                         </div>
                     </div>
                     <div class="row">
                         <div class="col-sm-6 py-2">
                             <p id="copyright">&copy; 2021 <a href="https://macodeid.com/">Prishtine</a>. All rights reserved</p>
                         </div>
                         <div class="col-sm-6 py-2 text-right">
                             <div class="d-inline-block px-3">
                                 <a href="#">Privacy</a>
                             </div>
                             <div class="d-inline-block px-3">
                                 <a href="#">Contact Us</a>
                             </div>
                         </div>
                     </div>
                 </div>
             </footer>
         }
     </div>
     @Scripts.Render("~/bundles/jquery")
     @Scripts.Render("~/bundles/bootstrap")
     @RenderSection("scripts", required: false)

 </body>
 </html>